name: TrollV4
version: '${project.version}'
main: de.presti.trollv4.main.TrollV4
author: Presti
softdepend:
   - ProtocolLib
   - LibsDisguises
   - NoteBlockAPI
website: https://presti.me
api-version: 1.13
folia: true
commands:
   troll:
      description: The Troll command.
      aliases:
         - trollv4
         - prank
         - prankv4