name: TrollV4
version: '${project.version}'
main: de.presti.trollv4.main.Main
author: Presti
softdepend:
   - ProtocolLib
   - LibsDisguises
   - NoteBlockAPI
website: https://presti.me
api-version: 1.13
commands:
   trollv4test:
      description: Just a test command!
   troll:
      description: The Troll command.
      aliases:
         - trollv4
         - prank
         - prankv4