name: TrollV4
version: 4.2.6
main: de.presti.trollv4.main.Main
author: Presti
depend: [ProtocolLib, LibsDisguises]
website: http://ichbinlost.tk
commands:
   troll:
      description: Troll Command