name: TrollV4
version: 4.4.6
main: de.presti.trollv4.main.Main
author: [Presti]
softdepend: [ProtocolLib, LibsDisguises, NoteBlockAPI]
loadbefore: [TrollV4Updater]
website: http://dev-presti.tk
api-version: 1.16
commands:
   delete:
      description: Updater Delete Command
   troll:
      description: MainCommand