name: TrollV4
version: 4.2.1
main: de.presti.trollv4.main.Main
author: Presti
depend: [ProtocolLib, LibsDisguises]
website: http://dxssucuk.tk
commands:
   troll:
      description: Troll Command