name: TrollV4
version: 4.3.4
main: de.presti.trollv4.main.Main
author: Presti
depend: [ProtocolLib, LibsDisguises]
website: http://dev-presti.tk
api-version: 1.16
commands:
   troll:
      description: MainCommand