name: TrollV4
version: '${project.version}'
main: de.presti.trollv4.main.Main
author: Presti
depend:
   - ProtocolLib
softdepend:
   - LibsDisguises
   - NoteBlockAPI
   - NPCLibPlugin
loadbefore: [TrollV4Updater]
website: https://presti.me
api-version: 1.13
commands:
   delete:
      description: Delete command for the automatic Updater.
   troll:
      description: The Troll command.