name: TrollV4
version: 4.5.7
main: de.presti.trollv4.main.Main
author: [Presti, David]
depend: [ProtocolLib]
softdepend: [LibsDisguises, NoteBlockAPI, NPCLibPlugin]
loadbefore: [TrollV4Updater]
website: https://presti.me
api-version: 1.13
commands:
   delete:
      description: Delete command for the Automatic Updater.
   troll:
      description: The Main Troll Command.